apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: adjust_cluster_definition_path.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: "as-gf-.*"
