apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
  - ../../base

patchesJSON6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-gitops-operator
      namespace: openshift-operators
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'gitops-1.8'
